CREATE TABLE customer (
    id    bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    house varchar(255),
    street varchar(255),
    city varchar(255),
    postcode varchar(20),
    PRIMARY KEY (id)
);
CREATE TABLE product (
    id    bigint GENERATED BY DEFAULT AS IDENTITY,
    price decimal(19, 2) NOT NULL,
    sku   varchar(255),
    description  varchar(255), 
    PRIMARY KEY (id)
);
ALTER TABLE product
    ADD CONSTRAINT UK_q1mafxn973ldq80m1irp3mpvq UNIQUE (sku);
 
CREATE TABLE customer_geolocation (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_customer_geolocation_customer FOREIGN KEY (customer_id)
        REFERENCES customer (id)
        ON DELETE CASCADE
);
